# Generated by Django 3.0.8 on 2020-07-10 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_bookinstance_borrower'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'permissions': [('can_add', 'Can add new author in DB'), ('can_delete', 'Can delete author from DB'), ('can_edit', 'Can edit author data into DB')]},
        ),
    ]
