# Generated by Django 3.0.8 on 2020-07-11 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20200711_0104'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('can_add_book', 'Can add book inot book table (USER_ADDED_PERMISSION)'), ('can_edit_book', 'Can edit book parameters into book table (USER_ADDED_PERMISSION)'), ('can_delete_book', 'Cam delete book from book table (USER_ADDED_PERMISSION)')]},
        ),
    ]
